#!/usr/bin/env bash
# Display listening ports along with PID and program name

echo "Active Internet connections (only servers)"
echo "Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name"

# Display TCP listening ports
netstat -tuln | grep '^tcp' | awk '{print $1, $4, $7}' | while read line; do
    proto=$(echo $line | awk '{print $1}')
    local_address=$(echo $line | awk '{print $2}')
    pid=$(echo $line | awk '{print $3}')
    program=$(ps -p $pid -o comm=)
    echo "$proto $local_address *:* LISTEN $pid/$program"
done

# Display UDP listening ports
netstat -uln | grep '^udp' | awk '{print $1, $4, $6}' | while read line; do
    proto=$(echo $line | awk '{print $1}')
    local_address=$(echo $line | awk '{print $2}')
    pid=$(echo $line | awk '{print $3}')
    program=$(ps -p $pid -o comm=)
    echo "$proto $local_address *:* $pid/$program"
done

echo "Active UNIX domain sockets (only servers)"
echo "Proto RefCnt Flags       Type       State         I-Node   PID/Program name    Path"

# Display UNIX domain sockets
netstat -xln | grep '^unix' | awk '{print $1, $2, $7}' | while read line; do
    proto=$(echo $line | awk '{print $1}')
    i_node=$(echo $line | awk '{print $6}')
    pid=$(echo $line | awk '{print $7}')
    program=$(ps -p $pid -o comm=)
    echo "$proto 2 [ACC] STREAM LISTENING $i_node $pid/$program *"
done
