#!/usr/bin/env bash
# Set the internal field separator to ':'

IFS=":"

# Read the /etc/passwd file line by line
while read -r username password uid gid info home shell; do
    # Extract user information
    echo "The user $username is part of the $gid gang, lives in $home and rides $shell. $uid's place is protected by the passcode $password, more info about the user here: $info"
done < /etc/passwd

