#!/usr/bin/env bash
# Best School 10 times, but after nine times, display Hi then continue

i=0
while [ $i -lt 10 ]; do
  if [ $i -eq 8 ]; then
    echo "Best School"
    echo "Hi"
  else
    echo "Best School"
  fi
  ((i++))
done
