#!/usr/bin/env bash

# Displaying content of the current directory
# Only the part of the name after the first dash is displayed

for file in *; do
  if [ -f "$file" ] && [[ "$file" != .* ]]; then
    # Extracting part of the name after the first dash
    name=$(echo "$file" | cut -d '-' -f 2-)
    echo "$name"
   fi
done
